#!/bin/sh
$FLEX_HOME/bin/mxmlc -compiler.library-path=./Box2DFlexLib/bin/:$FLEX_HOME/frameworks/libs/:$FLEX_HOME/frameworks/locale/en_US/ Bench2d.mxml
$FLEX_HOME/bin/mxmlc -compiler.library-path=./NapeLib/bin/:$FLEX_HOME/frameworks/libs/:$FLEX_HOME/frameworks/locale/en_US/ Bench2dNape.mxml
